// Auto-generated by Supabase CLI — run: npx supabase gen types typescript --local
// This is a placeholder until Supabase is running locally
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Relationships: [];
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          timezone: string;
          morning_plan_time: string;
          eod_report_time: string;
          push_subscription: Json | null;
          slack_channels: string[] | null;
          preferences: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          timezone?: string;
          morning_plan_time?: string;
          eod_report_time?: string;
          push_subscription?: Json | null;
          slack_channels?: string[] | null;
          preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          timezone?: string;
          morning_plan_time?: string;
          eod_report_time?: string;
          push_subscription?: Json | null;
          slack_channels?: string[] | null;
          preferences?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Relationships: [];
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          priority: 'low' | 'medium' | 'high';
          effort: 'xs' | 's' | 'm' | 'l' | 'xl' | null;
          estimated_minutes: number | null;
          status: 'pending' | 'in_progress' | 'done' | 'cancelled';
          is_movable: boolean;
          source: 'manual' | 'slack' | 'ai_suggested';
          source_ref: Json | null;
          scheduled_date: string | null;
          scheduled_start: string | null;
          scheduled_end: string | null;
          due_date: string | null;
          completed_at: string | null;
          ai_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          title: string;
          id?: string;
          description?: string | null;
          priority?: 'low' | 'medium' | 'high';
          effort?: 'xs' | 's' | 'm' | 'l' | 'xl' | null;
          estimated_minutes?: number | null;
          status?: 'pending' | 'in_progress' | 'done' | 'cancelled';
          is_movable?: boolean;
          source?: 'manual' | 'slack' | 'ai_suggested';
          source_ref?: Json | null;
          scheduled_date?: string | null;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          due_date?: string | null;
          completed_at?: string | null;
          ai_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          priority?: 'low' | 'medium' | 'high';
          effort?: 'xs' | 's' | 'm' | 'l' | 'xl' | null;
          estimated_minutes?: number | null;
          status?: 'pending' | 'in_progress' | 'done' | 'cancelled';
          is_movable?: boolean;
          source?: 'manual' | 'slack' | 'ai_suggested';
          source_ref?: Json | null;
          scheduled_date?: string | null;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          due_date?: string | null;
          completed_at?: string | null;
          ai_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Relationships: [];
        Row: {
          id: string;
          user_id: string;
          channel: 'push' | 'email' | 'in_app';
          title: string;
          body: string;
          ref_type: 'task' | 'event' | 'schedule' | 'report';
          ref_id: string | null;
          scheduled_for: string;
          sent_at: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          channel: 'push' | 'email' | 'in_app';
          title: string;
          body: string;
          ref_type: 'task' | 'event' | 'schedule' | 'report';
          scheduled_for: string;
          id?: string;
          ref_id?: string | null;
          sent_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          channel?: 'push' | 'email' | 'in_app';
          title?: string;
          body?: string;
          ref_type?: 'task' | 'event' | 'schedule' | 'report';
          ref_id?: string | null;
          scheduled_for?: string;
          sent_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
      };
      slack_task_suggestions: {
        Relationships: [];
        Row: {
          id: string;
          user_id: string;
          channel_id: string;
          channel_name: string;
          message_ts: string;
          message_text: string;
          suggested_title: string;
          suggested_priority: 'low' | 'medium' | 'high';
          suggested_effort: 'xs' | 's' | 'm' | 'l' | 'xl' | null;
          confidence: number;
          reasoning: string;
          status: 'pending' | 'accepted' | 'dismissed';
          task_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          channel_id: string;
          channel_name: string;
          message_ts: string;
          message_text: string;
          suggested_title: string;
          suggested_priority: 'low' | 'medium' | 'high';
          confidence: number;
          reasoning: string;
          id?: string;
          suggested_effort?: 'xs' | 's' | 'm' | 'l' | 'xl' | null;
          status?: 'pending' | 'accepted' | 'dismissed';
          task_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          channel_id?: string;
          channel_name?: string;
          message_ts?: string;
          message_text?: string;
          suggested_title?: string;
          suggested_priority?: 'low' | 'medium' | 'high';
          suggested_effort?: 'xs' | 's' | 'm' | 'l' | 'xl' | null;
          confidence?: number;
          reasoning?: string;
          status?: 'pending' | 'accepted' | 'dismissed';
          task_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_secrets: {
        Relationships: [];
        Row: {
          id: string;
          user_id: string;
          google_refresh_token: string | null;
          google_access_token: string | null;
          google_token_expires_at: string | null;
          slack_bot_token: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          id?: string;
          google_refresh_token?: string | null;
          google_access_token?: string | null;
          google_token_expires_at?: string | null;
          slack_bot_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          google_refresh_token?: string | null;
          google_access_token?: string | null;
          google_token_expires_at?: string | null;
          slack_bot_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      task_priority: 'low' | 'medium' | 'high';
      task_effort: 'xs' | 's' | 'm' | 'l' | 'xl';
      task_status: 'pending' | 'in_progress' | 'done' | 'cancelled';
      task_source: 'manual' | 'slack' | 'ai_suggested';
      notification_channel: 'push' | 'email' | 'in_app';
      notification_ref_type: 'task' | 'event' | 'schedule' | 'report';
      schedule_status: 'draft' | 'active' | 'completed';
      chat_role: 'user' | 'assistant';
      slack_suggestion_status: 'pending' | 'accepted' | 'dismissed';
    };
  };
}
